---
version: '3.7'
services:

  app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - 8443:8443
    env_file: .env
    environment:
      REDIS_URI: redis://redis:6379/

  postgres:
    image: 'postgres:14'
