"""add indexes

Revision ID: caf538bddc17
Revises: 2cb5310b9cea
Create Date: 2022-10-03 17:35:41.359562

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "caf538bddc17"
down_revision = "2cb5310b9cea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_comment_post_id"), "comment", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_timestamp"), "post", ["timestamp"], unique=False)
    op.create_index(op.f("ix_post_user_login"), "post", ["user_login"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_user_login"), table_name="post")
    op.drop_index(op.f("ix_post_timestamp"), table_name="post")
    op.drop_index(op.f("ix_comment_post_id"), table_name="comment")
    # ### end Alembic commands ###
